version: '3.8'

services:
  # 1. Keycloak Service (The "IAM")
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      # hosted at 8180
      - "8180:8080"
    networks:
      - opm-network

  # 2. Backend Service (Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/opm-realm
    networks:
      - opm-network
    depends_on:
      - keycloak

  # 3. Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - opm-network
    depends_on:
      - backend

networks:
  opm-network:
    driver: bridge
